-- 초기 스키마: JPA 엔티티의 매핑(테이블·컬럼·제약조건·@Index)과 같게 맞춘다. prod는 ddl-auto=validate로 대조한다.
-- 이미 적용된 마이그레이션은 수정하지 않는다. 스키마를 바꿀 때는 V2__...sql처럼 새 파일을 추가한다.

CREATE TABLE users (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    deleted_at TIMESTAMP(6),
    name       VARCHAR(255) NOT NULL,
    email      VARCHAR(255) NOT NULL,
    password   VARCHAR(255) NOT NULL,
    role       VARCHAR(255) NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT users_role_check CHECK (role IN ('OWNER', 'MEMBER'))
);

CREATE TABLE invite_codes (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at    TIMESTAMP(6) NOT NULL,
    updated_at    TIMESTAMP(6) NOT NULL,
    deleted_at    TIMESTAMP(6),
    code          VARCHAR(255) NOT NULL,
    max_uses      INTEGER      NOT NULL,
    used_count    INTEGER      NOT NULL,
    created_by_id BIGINT       NOT NULL,
    CONSTRAINT invite_codes_pkey PRIMARY KEY (id),
    CONSTRAINT uk_invite_codes_code UNIQUE (code),
    CONSTRAINT fk_invite_codes_created_by FOREIGN KEY (created_by_id) REFERENCES users (id)
);

CREATE TABLE schedules (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at  TIMESTAMP(6) NOT NULL,
    updated_at  TIMESTAMP(6) NOT NULL,
    deleted_at  TIMESTAMP(6),
    title       VARCHAR(255) NOT NULL,
    start_time  TIMESTAMP(6) NOT NULL,
    end_time    TIMESTAMP(6) NOT NULL,
    status      VARCHAR(255) NOT NULL,
    assignee_id BIGINT,
    CONSTRAINT schedules_pkey PRIMARY KEY (id),
    CONSTRAINT schedules_status_check CHECK (status IN ('PLANNED', 'DONE', 'CANCELED')),
    CONSTRAINT fk_schedules_assignee FOREIGN KEY (assignee_id) REFERENCES users (id)
);

CREATE TABLE tasks (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at   TIMESTAMP(6) NOT NULL,
    updated_at   TIMESTAMP(6) NOT NULL,
    deleted_at   TIMESTAMP(6),
    title        VARCHAR(255) NOT NULL,
    is_recurring BOOLEAN      NOT NULL,
    status       VARCHAR(255) NOT NULL,
    assignee_id  BIGINT,
    CONSTRAINT tasks_pkey PRIMARY KEY (id),
    CONSTRAINT tasks_status_check CHECK (status IN ('TODO', 'DONE')),
    CONSTRAINT fk_tasks_assignee FOREIGN KEY (assignee_id) REFERENCES users (id)
);

CREATE TABLE expenses (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at  TIMESTAMP(6)   NOT NULL,
    updated_at  TIMESTAMP(6)   NOT NULL,
    deleted_at  TIMESTAMP(6),
    category    VARCHAR(255)   NOT NULL,
    amount      NUMERIC(38, 2) NOT NULL,
    due_date    DATE           NOT NULL,
    paid_status BOOLEAN        NOT NULL,
    memo        VARCHAR(255),
    CONSTRAINT expenses_pkey PRIMARY KEY (id)
);

CREATE TABLE shared_notes (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at  TIMESTAMP(6) NOT NULL,
    updated_at  TIMESTAMP(6) NOT NULL,
    deleted_at  TIMESTAMP(6),
    title       VARCHAR(255) NOT NULL,
    content     TEXT         NOT NULL,
    category    VARCHAR(255) NOT NULL,
    assignee_id BIGINT,
    CONSTRAINT shared_notes_pkey PRIMARY KEY (id),
    CONSTRAINT fk_shared_notes_assignee FOREIGN KEY (assignee_id) REFERENCES users (id)
);

-- 조회 조건·정렬에 쓰이는 컬럼. users.email, invite_codes.code는 UNIQUE 제약이 인덱스를 만든다
CREATE INDEX idx_schedules_start_time ON schedules (start_time);  -- 기간과 겹치는 일정 조회, 시작 시각 정렬
CREATE INDEX idx_tasks_assignee_id ON tasks (assignee_id);         -- 담당자별 할 일 조회
CREATE INDEX idx_shared_notes_category ON shared_notes (category); -- 카테고리별 메모 조회
CREATE INDEX idx_expenses_due_date ON expenses (due_date);         -- 납부일 순 지출 목록
