-- 초기 스키마: 로컬 DB(Hibernate ddl-auto=update로 생성)의 테이블 구조를 그대로 옮겼다.
-- 이미 적용된 마이그레이션은 수정하지 않는다. 스키마를 바꿀 때는 V2__...sql처럼 새 파일을 추가한다.

CREATE TABLE users (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    deleted_at TIMESTAMP(6),
    name       VARCHAR(255) NOT NULL,
    email      VARCHAR(255) NOT NULL,
    password   VARCHAR(255) NOT NULL,
    role       VARCHAR(255) NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT users_role_check CHECK (role IN ('OWNER', 'MEMBER'))
);

CREATE TABLE invite_codes (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at    TIMESTAMP(6) NOT NULL,
    updated_at    TIMESTAMP(6) NOT NULL,
    deleted_at    TIMESTAMP(6),
    code          VARCHAR(255) NOT NULL,
    max_uses      INTEGER      NOT NULL,
    used_count    INTEGER      NOT NULL,
    created_by_id BIGINT       NOT NULL,
    CONSTRAINT invite_codes_pkey PRIMARY KEY (id),
    CONSTRAINT uk_invite_codes_code UNIQUE (code),
    CONSTRAINT fk_invite_codes_created_by FOREIGN KEY (created_by_id) REFERENCES users (id)
);

CREATE TABLE schedules (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at  TIMESTAMP(6) NOT NULL,
    updated_at  TIMESTAMP(6) NOT NULL,
    deleted_at  TIMESTAMP(6),
    title       VARCHAR(255) NOT NULL,
    start_time  TIMESTAMP(6) NOT NULL,
    end_time    TIMESTAMP(6) NOT NULL,
    status      VARCHAR(255) NOT NULL,
    assignee_id BIGINT,
    CONSTRAINT schedules_pkey PRIMARY KEY (id),
    CONSTRAINT schedules_status_check CHECK (status IN ('PLANNED', 'DONE', 'CANCELED')),
    CONSTRAINT fk_schedules_assignee FOREIGN KEY (assignee_id) REFERENCES users (id)
);

CREATE TABLE tasks (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at   TIMESTAMP(6) NOT NULL,
    updated_at   TIMESTAMP(6) NOT NULL,
    deleted_at   TIMESTAMP(6),
    title        VARCHAR(255) NOT NULL,
    is_recurring BOOLEAN      NOT NULL,
    status       VARCHAR(255) NOT NULL,
    assignee_id  BIGINT,
    CONSTRAINT tasks_pkey PRIMARY KEY (id),
    CONSTRAINT tasks_status_check CHECK (status IN ('TODO', 'DONE')),
    CONSTRAINT fk_tasks_assignee FOREIGN KEY (assignee_id) REFERENCES users (id)
);

CREATE TABLE expenses (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at  TIMESTAMP(6)   NOT NULL,
    updated_at  TIMESTAMP(6)   NOT NULL,
    deleted_at  TIMESTAMP(6),
    category    VARCHAR(255)   NOT NULL,
    amount      NUMERIC(38, 2) NOT NULL,
    due_date    DATE           NOT NULL,
    paid_status BOOLEAN        NOT NULL,
    memo        VARCHAR(255),
    CONSTRAINT expenses_pkey PRIMARY KEY (id)
);

CREATE TABLE shared_notes (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at  TIMESTAMP(6) NOT NULL,
    updated_at  TIMESTAMP(6) NOT NULL,
    deleted_at  TIMESTAMP(6),
    title       VARCHAR(255) NOT NULL,
    content     TEXT         NOT NULL,
    category    VARCHAR(255) NOT NULL,
    assignee_id BIGINT,
    CONSTRAINT shared_notes_pkey PRIMARY KEY (id),
    CONSTRAINT fk_shared_notes_assignee FOREIGN KEY (assignee_id) REFERENCES users (id)
);
